language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "lequal"
    token:
      secure: "WhaivOMQdhKdJQEayRLyoBhKbqaLIGD1PzP3jrlcDWmZHTFF4uk4Q6TuJ6iuDXIgPy4eaKG1UQedQcN+KAEMljNYVDFEL4Q/a5P4n31yz4guXCvQKjdzxy1OLmAeYmRosgLmmF/pfL0qHFSIIDKxDZFwP3z1yZHZ2cpWdAXQlR7vEZXpsewOMM2BylH0eGR/LOxbp8nWTg0/5+nELfUoB0iWb7+iWj3u+SiwvH3WVqAYOuUpZguHaAUA5b7WX4gvcoRSMpp8ee5JEJmyiNgmU00BAtBtHKwc06yz9VYKmYtib8IfXfgXtsBd52LqmGH/qk++nOMBWgSQgTjhBAr88oRfnA1oLw+Hgay+nOIfQoto3X8l5d0aWkqdGwzm9pOv5KzB8MFcVSGYKtafV5hiugLor7YGS18sG0crCLiCseWxTkxzUDbDSxnVaR7cpv42a2fbgdHgzip2mDs1gdBwxaUsleT2EdeQPoJ6JeiTfCbYmuQm5xx0WL16DdYb8rLnT4sAPqbaMnbIAJW+MgBMTBOyRczJrdC/n2YR+fcd+eIyXopUNWBILjWTjupoQuiZLoJMzk3LOOu0Tc+Dyqy8udaG5YpgQzMZDRwinXy7K3dU1/ryG9j+wIbzxh/tyFh/QNdi+AkBSL4/Vhy3vFIXNr0fmSWSw2Z5OMUfQGTXrmM="
      
jdk:
  - oraclejdk8
  
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
